### ISSUE TITLE
Fails to login

### ISSUE THREAD

**Issue by lavish440** [udbhav1/GPG-Messenger#14]
When I run app.py, it fails to login with the following traceback:
```python
Logging in foo@bar.com...
Attempt #1 failed, retrying
Traceback (most recent call last):
  File "/home/lavish/.local/lib/python3.12/site-packages/fbchat/_client.py", line 205, in login
    self._state = State.login(
                  ^^^^^^^^^^^^
  File "/home/lavish/.local/lib/python3.12/site-packages/fbchat/_state.py", line 153, in login
    raise _exception.FBchatUserError(
fbchat._exception.FBchatUserError: Login failed. Check email/password. (Failed on url: https://m.facebook.com/login.php?login_attempt=1)
Attempt #2 failed, retrying
Traceback (most recent call last):
  File "/home/lavish/.local/lib/python3.12/site-packages/fbchat/_client.py", line 205, in login
    self._state = State.login(
                  ^^^^^^^^^^^^
  File "/home/lavish/.local/lib/python3.12/site-packages/fbchat/_state.py", line 153, in login
    raise _exception.FBchatUserError(
fbchat._exception.FBchatUserError: Login failed. Check email/password. (Failed on url: https://m.facebook.com/login.php?login_attempt=1)
^CTraceback (most recent call last):
  File "/home/lavish/git/GPG-Messenger/app.py", line 2, in <module>
    import messenger
  File "/home/lavish/git/GPG-Messenger/messenger.py", line 316, in <module>
    client = make_client()
             ^^^^^^^^^^^^^
  File "/home/lavish/git/GPG-Messenger/messenger.py", line 178, in make_client
    client = GPGClient(config["username"], get_pass(config["pass"]), session_cookies=cookies)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lavish/.local/lib/python3.12/site-packages/fbchat/_client.py", line 103, in __init__
    self.login(email, password, max_tries, user_agent=user_agent)
  File "/home/lavish/.local/lib/python3.12/site-packages/fbchat/_client.py", line 205, in login
    self._state = State.login(
                  ^^^^^^^^^^^^
  File "/home/lavish/.local/lib/python3.12/site-packages/fbchat/_state.py", line 139, in login
    r = session.post("https://m.facebook.com/login.php?login_attempt=1", data=data)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1252, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1104, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

```

**Comment by udbhav1** [comment]
this project has been unmaintained for five years and it looks like the library used to simulate a facebook login (which is also unmaintained) no longer works.

**Comment by lavish440** [comment]
Any similar project that still works?

**Comment by stephen-huan** [comment]
It depends on what your goals are. If you just want a end-to-end encrypted messaging service, I recommend [Signal](https://signal.org/).

If you want end-to-end encryption over Facebook Messenger specifically (or some other chat platform) it may be possible to use the [Matrix](https://matrix.org/) protocol which supports [encryption](https://matrix.org/docs/matrix-concepts/end-to-end-encryption/) and [bridge](https://matrix.org/ecosystem/bridges/) over Messenger. I do not personally use Matrix and have never tried this, so I can't say whether this is practical but it should theoretically be possible.

**Comment by lavish440** [comment]
I personally want a GPG based social messaging app.

**Comment by stephen-huan** [comment]
Have you tried email? ;)

In seriousness, there are cryptographic as well as practical reasons not to use GPG. See this [blog post](https://moxie.org/2015/02/24/gpg-and-me.html) by Moxie. I don't know why you want GPG in particular, but I would seriously consider using a messaging protocol based on modern cryptography like the [Double Ratchet](https://signal.org/docs/specifications/doubleratchet/) (disclaimer: I am not a cryptography expert).
